### ISSUE TITLE
root-riscv32-toolchain.bin does not exist

### ISSUE THREAD

**Issue by kavalsky** [bucaps/marss-riscv#1]
Thie simulator looks for this as the image file when booting, however the image file that is downloaded, is named risv32.img, 

So, before running, I created a sym link from riscv32.img to root-riscv32-toolchain.bin, and booted successfully.

Another option is to change the string in riscvemu.cfg (probably better)

**Comment by gkothar1** [comment]
Thank you for notifying us! I have fixed the string in riscvemu.cfg
