### ISSUE TITLE
Extra `floor`: function is applied to an integer argument

### ISSUE THREAD

**Issue by aka-sps** [bucaps/marss-riscv#12]
In https://github.com/bucaps/marss-riscv/blob/master/src/riscvsim/btb.c

https://github.com/bucaps/marss-riscv/blob/ddd086b445dfde4509e841b554ca9ccff9b5eed3/src/riscvsim/cache.c#L69
...
https://github.com/bucaps/marss-riscv/blob/ddd086b445dfde4509e841b554ca9ccff9b5eed3/src/riscvsim/cache.c#L109

and in https://github.com/bucaps/marss-riscv/blob/master/src/riscvsim/btb.c

https://github.com/bucaps/marss-riscv/blob/ddd086b445dfde4509e841b554ca9ccff9b5eed3/src/riscvsim/btb.c#L71
...
https://github.com/bucaps/marss-riscv/blob/ddd086b445dfde4509e841b554ca9ccff9b5eed3/src/riscvsim/btb.c#L129

**Comment by gkothar1** [comment]
Fixed in commit 98f2e5936b393e4753eec841dcb5c42f148d6c68
