### ISSUE TITLE
INS_TYPE_JAL counter is added twice in stats display

### ISSUE THREAD

**Issue by go-sc** [bucaps/marss-riscv#14]
In branch `temu-2019-12-21-port`, `src/stats_display.c:132`:
https://github.com/bucaps/marss-riscv/blob/820576eb5b2871e2d33dbeb793eb8ae8fe12da31/src/stats_display.c#L132
`GET_TOTAL_STAT(ins_type[INS_TYPE_JAL])` is added twice to `total_branches`. Probably, one of them should be replaced with `GET_TOTAL_STAT(ins_type[INS_TYPE_JALR])`.

**Comment by gkothar1** [comment]
closed in commit 82bc024044d54b2bdbf85dc16ef3d60e3183acae
