### ISSUE TITLE
RISC-V toolchain required?

### ISSUE THREAD

**Issue by gdessouky** [bucaps/marss-riscv#16]
Do you need a risc-v toolchain installed on the guest image to compile executables? It didn't seem so with the Coremark example...can you clarify how does this work?

**Comment by gkothar1** [comment]
You can refer to this [section](https://github.com/bucaps/marss-riscv#using-checkpoints) in the README file.

You can compile the programs with the simulation markers on your host x86 machine using the RISC-V toolchain and import them onto the disk image using the `scp` command.

When you are in guest machine terminal type:
```console
$ scp -r <host-system-uername>@10.0.2.2:<absolute path to executable on host> <destination location on disk image>
```
