### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by gdessouky** [bucaps/marss-riscv#17]
Hey! How long would these benchmarks https://github.com/rv8-io/rv8-bench/tree/master/src take in a cycle-accurate simulation on marrs-riscv? Just curious to know time estimates.

**Comment by gkothar1** [comment]
It depends on simulation parameters and delays you specify in the config file. Example config file is [here](https://marss-riscv-docs.readthedocs.io/en/latest/sections/running-full-system.html#configuring-the-simulator).
