### ISSUE TITLE
Running executable on MARSS

### ISSUE THREAD

**Issue by Navko** [bucaps/marss-riscv#20]
Hi Am new to RISCV
Is it possible to run an application without Kernel Image? i.e like direct executable?

**Comment by gkothar1** [comment]
Hi,

The current version doesn't support direct executables, you need to run the apps using kernel image.

You can find 32-bit and 64-bit bootloader, kernel, and disk image here: [https://cs.binghamton.edu/~marss-riscv/marss-riscv-images.tar.gz](https://cs.binghamton.edu/~marss-riscv/marss-riscv-images.tar.gz)

Regards,
Gaurav

**Comment by Navko** [comment]
Thanks for replying
