### ISSUE TITLE
why max_clock_cycles are added 1 when store data (Simulation Mode)

### ISSUE THREAD

**Issue by Ruiggg** [bucaps/marss-riscv#22]
In `src/riscvsim/core/riscv_sim_cpu.c`: line 633, in function `mem_cpu_stage_exec`, the code is:
```c
if ((e->ins.is_store || e->ins.is_atomic_store))
{
                e->max_clock_cycles += 1;
                s->simcpu->mem_hierarchy->data_write_delay(
                    s->simcpu->mem_hierarchy, s->data_guest_paddr,
                    e->ins.bytes_to_rw, MEMORY, s->priv);
 }
```
why the `e->max_clock_cycles` is just added by 1 ?
I think it should be:
```c
e->max_clock_cycles += s->simcpu->mem_hierarchy->data_write_delay(
                    s->simcpu->mem_hierarchy, s->data_guest_paddr,
                    e->ins.bytes_to_rw, MEMORY, s->priv);
```

**Comment by gkothar1** [comment]
In the current model, all the memory write instructions (STORE types) exit memory (MEM) stage (of the CPU pipeline) in a single cycle. Hence `e->max_clock_cycles += 1;` 

The next following line of code just updates the state of the line (dirty) in the cache hierarchy, and submits a memory write request to the memory controller (based on cache write policy). **This happens asynchronously**. So the store type instructions don't have to wait in memory (MEM) stage.
```c
s->simcpu->mem_hierarchy->data_write_delay(
                    s->simcpu->mem_hierarchy, s->data_guest_paddr,
                    e->ins.bytes_to_rw, MEMORY, s->priv);
```

Alternatively, the following block of code will stall the STORE type instructions in memory stage until the entire write latency is simulated (upto the main memory). 
```c
e->max_clock_cycles += s->simcpu->mem_hierarchy->data_write_delay(
                    s->simcpu->mem_hierarchy, s->data_guest_paddr,
                    e->ins.bytes_to_rw, MEMORY, s->priv);
```

Its just a design choice.
Hope this clears out your confusion.

Regards,
Gaurav

**Comment by Ruiggg** [comment]
Thanks for replying
